package nl.jemaja.weekmenu.model;

public enum PlanRule {
	LONGEST,
	TWOWEEKRANDOM,
	CULINAIR,
	MEALPREP,
	LOWCOMPLEX_LONGEST,
	LOWCOMPLEX_TWOWEEKRANDOM,
	HEALTHY_LONGEST,
	HEALTHY_TWOWEEKRANDOM,
	RULE_BASED

}
